# Generated by Django 2.0.4 on 2018-11-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pages',
            field=models.CharField(max_length=15),
        ),
    ]
