# Generated by Django 2.0.4 on 2018-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPdf', '0003_file_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='watermark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
